import Head from "next/head";
import { getPosts } from "../services";
import { PostCard } from "../components";
import { motion } from "framer-motion";

export default function Home({ posts }) {

  const variants = {
    hidden: { opacity: 0 },
    visible: { opacity: 1 },
  };

  
  return (
    <div className="container mx-auto px-6 mb-8">
      <Head>
        <title>HCODES Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-1 gap-4 px-6">
        <motion.h1
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 2 }}
          className="text-5xl font-semibold mb-8 leading-relaxed lg:text-7xl lg:w-3/4 lg:float-left"
        >
          My Weekly{" "}
          <span className="text-green-500 text-transparent bg-clip-text bg-gradient-to-bl from-green-500 to-blue-900">
            Dev
          </span>{" "}
          Blog
        </motion.h1>
        <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3">
          {posts.map((post) => (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1,  }}
              transition={{ duration: 2 }}
              variants={variants}
              key={post.node.title}
            >
              <PostCard post={post.node} key={post.node.title} />
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];

  return {
    props: {
      posts,
    },
  };
}
