import Head from "next/head";
import { getPosts } from "../services";
import { PostCard } from "../components";

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div className="container mx-auto px-6 mb-8">
      <Head>
        <title>HCODES Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-1 gap-4 px-6">
        <h1 className="text-5xl font-semibold mb-8 leading-relaxed lg:text-7xl lg:w-3/4 lg:float-left">
          My Weekly{" "}
          <span className="text-green-500 text-transparent bg-clip-text bg-gradient-to-bl from-green-500 to-blue-900">
            Dev
          </span>{" "}
          Blog
        </h1>
        <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3">
          {posts.map((post) => (
            <PostCard post={post.node} key={post.node.title} />
          ))}
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];

  return {
    props: {
      posts,
    },
  };
}
